version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/blockchyp/blockchyp-go

    steps:
      - checkout

      - restore_cache:
          keys:
            - mod-{{ checksum "go.sum" }}

      - run:
          name: Build
          command: make build

      - run:
          name: Test
          command: make test

      - save_cache:
          key: mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

      - store_test_results:
          path: /go/src/github.com/blockchyp-blockchyp-go/build/test-reports

      - persist_to_workspace:
          root: build
          paths:
            - dist

  publish:
    docker:
      - image: cibuilds/github:0.12

    steps:
      - attach_workspace:
          at: build

      - run:
          name: Publish
          command: make publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
